vich_uploader:
    db_driver: orm

    mappings:
        produit_image:
            uri_prefix: /images/produits
            upload_destination: '%kernel.project_dir%/public/images/produits'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            directory_namer:
                service: Vich\UploaderBundle\Naming\CurrentDateTimeDirectoryNamer
                options:
                    date_time_format: 'Y/m'
                    date_time_property: updated_at
